version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ta5-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181   # Specify the client port for Zookeeper
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ta5-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - app_network

  streamer:
    build: .
    container_name: streamer
    environment:
      - SCRIPT=streamer
    depends_on:
      - kafka
    networks:
      - app_network

  lda_updater:
    build: .
    container_name: lda_updater
    environment:
      - SCRIPT=lda_updater
    depends_on:
      - kafka
    networks:
      - app_network

networks:
  app_network:
    driver: bridge